config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#top'

  get 'books/about'

  get 'books/top'

  get 'users/index' => 'users#index'

  patch '/books/:id' => 'books#update', as: 'update_book'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit]

  resources :users, only: [:new, :create, :index, :show, :destroy, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

validates :title, presence: true

validates :body, presence: true

validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :books, dependent: :destroy

attachment :profile_image

validates :username, length: { minimum: 2, maximum: 20 }

validates :introduction, length: { maximum: 50 }

 def email_required?
   false
 end

 def email_changed?
   false
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
 end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!,
 only: [:index, :show, :new, :create, :update, :edit, :destroy, :update]

  def index
    @books = Book.all
    @book = Book.new
    @user = User.all
  end

  def about
  end

  def show
    @book_params = Book.find(params[:id])
    @books = Book.all
    @book = Book.new
    @user = User.all
    @users = @book_params.user
  end

  def new
    @books = Book.all
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     @user = current_user
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        @user = User.all
        render :index
      end
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
      redirect_to books_path
      end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  def update
      @book = Book.find(params[:id])
      @book.update(book_params)
      redirect_to book_path(@book.id)
  end

    private
    def book_params
      params.require(:book).permit(:title, :body)
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.all
    @users = User.find(params[:id])
    @books = @users.books.page(params[:page])
    @book = Book.new
  end

  def index
    @user = User.all
    @book = Book.new
  end

  def new
    @books = Book.all
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     @user = current_user
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        redirect_to books_path
      end
  end

  def edit
     @user = User.find(params[:id])
      if @user.id != current_user.id
      redirect_to users_path
    end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "introduction was successfully edited."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

private
def user_params
    params.require(:user).permit(:user, :username, :profile_image, :introduction)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span class="title">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to " Home", user_path(current_user.id), class: 'glyphicon glyphicon-home home' %>
      </li>
      <li>
        <%= link_to " Users", "/users/index", class: 'glyphicon glyphicon-user users' %>
      </li>
      <li>
        <%= link_to " Books", "/books/", class: 'glyphicon glyphicon-book books' %>
      </li>
      <li>
        <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
      </li>
    <% else %>
      <li>
        <%= link_to " Home", "/", class: 'glyphicon glyphicon-home home' %>
      </li>
      <li>
        <%= link_to " About", '/books/about', class: 'glyphicon glyphicon-link about' %>
      </li>
      <li>
        <%= link_to " sign up", "/users/sign_up", class: 'glyphicon glyphicon-edit sign_up' %>
      </li>
      <li>
        <%= link_to " login", "/users/sign_in", class: 'glyphicon glyphicon-log-in sign_in' %>
      </li>
    <% end %>
    </ul>
    </nav>
  </div>
</header>

app/views/books/_profile.html.erb

    <div class='body'>
      <div class='container'>

  <div id="error_explanation">
<% if @book.errors.any? %>
    <ul>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
  </div>

      <p id="notice">
        <% if flash[:notice] %>
          <%= flash[:notice] %>
        <% end %>
      </p>

        <div class='row'>
    <div class="col-lg-3">
<h2>User info</h2>

<div class="profile-container">

  <table class='table'>
    <tr>
       <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "sample-author1.jpg" %>
    </tr>
    <tr>
        <th>name</th>
        <th>
          <%= current_user.username %>
        </th>
      <tr>
        <th>introduction</th>
        <th>
          <%= current_user.introduction %>
        </th>
      </tr>
</table>

<div class='row'>
      <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %>
</div>

</div>

<h3>New book</h3>

<%= form_for(@book) do |f| %>

<div class="field row">
<label for="user_name">Title</label>
<%= f.text_field :title, class: "col-xs-12 book_title" %>
</div>

<div class="field row">
<label for="user_name">Opinion</label>
<%= f.text_area :body, class: "col-xs-12 book_body" %>
</div>

<div class="field row">
<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
<% end %>
</div>

</div>

app/views/books/about.html.erb
<%= render 'books/header', books: @books %>

    <div class='body'>
      <div class='container'>

        <p id="notice"></p>
        <p id="notice"></p>

        <div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>

    </div>
    </div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/books/edit.html.erb
<%= render 'books/header', books: @books %>

    <div class='body'>
      <div class='container'>

        <p id="notice"></p>
        <p id="notice"></p>

      	<div class='row'>
	<div class='col-md-6 col-md-offset-3'>

		<h1>Editing Book</h1>
	<%= form_for(@book) do |f| %>
	<div class="field row">
    <label for="book_title">Title</label>
    	<%= f.text_field :title, class: 'col-xs-12 book_title' %>
  	</div>

	<div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
	</div>

  <div class="actions row">
    <%= f.submit 'Update Book', class: 'btn btn-primary col-xs-12' %>
  </div>

	<% end %>

		<%= link_to "Show", book_path(@book.id), class: "show_#{@book.id}" %> |
		<a href="/books" class="back">Back</a>
    </div>

    </div>
    </div>
    </div>
    </div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
<%= render 'books/header', books: @books %>

<%= render 'books/profile', books: @books %>

<div class="col-lg-9">

    <h2>Books</h2>

    <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 <% @books.each do |book| %>
      <tr>
        <td>
    <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "sample-author1.jpg" %>
    </td>
        <td><%= link_to "#{book.title}", "#{book_path(book.id)}", class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
 <% end %>
  </tbody>
</table>

</div>
</div>
</div>
    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/books/new.html.erb
<%= render 'books/header', books: @books %>

<%= render 'books/profile', books: @books %>

<div class="col-lg-9">
<h3>Books</h3>
</div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<%= render 'books/header', books: @books %>

<%= render 'books/profile', books: @books %>

<div class="col-lg-9">

<h2>Book detail</h2>

	<table class='table'>
		<tr>
    	<td><%= attachment_image_tag @users, :profile_image, size: "40x40", format: 'jpeg', fallback: "sample-author1.jpg" %>
        <br>
        <%= link_to "#{@users.username}", user_path(@users.id), class: "user_#{@users.id}" %></td>
    	<td><%= @book_params.title %></td>
    	<td><%= @book_params.body %></td>
      <% if @book_params.user == current_user %>
      <td>
        <%= link_to "Edit", edit_book_path(@book_params), class: "btn-sm btn-success edit_book_#{@book_params.id}" %></td>
      <td>
        <%= link_to "Destroy", book_path(@book_params), method: :delete, "data-confirm" => "Are you sure?", class: "btn-sm btn-danger destroy_book_#{@book_params.id}" %></td>
      <% end %>
    </tr>
    </table>
  </div>
</div>
</div>
</div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/books/top.html.erb
<%= render 'books/header', books: @books %>

    <div class='body'>
      <div class='container'>

        <p id="notice"></p>
        <p id="notice"></p>

        <div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>,<br>
          you can share and exchange  your opinions , inpressions , and emotions<br>
          about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <%= link_to "Log in", "users/sign_in", class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
      </div>
      <div class="row">
        <%= link_to "Sign Up", "users/sign_up", class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
      </div>
    </div>
  </div>
</div>

      </div>
    </div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= render 'books/header', books: @books %>

<div class='body'>
  <div class='container'>
    <p id="notice"></p>
        <h3>User info</h3>
    <div id="error_explanation">
<% if @user.errors.any? %>
    <ul>
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
  </div>

<%= form_for(@user) do |f| %>
    <label for="user_name">Name</label>
    <%= f.text_field :username, autofocus: true, id:"inputEmail", placeholder:"username", class: 'name' %>
    <label for="user_name">Image</label>
    <%= f.attachment_field :profile_image, autofocus: true, id:"inputEmail", placeholder: "image", class: 'user_image' %>
    <label for="user_name">introduction</label>
    <%= f.text_area :introduction, autofocus: true, id:"inputEmail", class: 'introduction' %>
    <br>
    <%= f.submit 'User Update' %>
<% end %>

</div>
</div>
    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<%= render 'books/header', books: @books %>

<%= render 'books/profile', books: @books %>

<div class="col-lg-9">
<h2>Users</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @user.each do |user| %>
<tr>
  <td>
    <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "sample-author1.jpg" %>
  </td>
  <td>
<%= user.username %>
  </td>
  <td>
<%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %>
  </td>
<% end %>
</tbody>
</table>

<br>
</div>
</div>
</div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<%= render 'books/header', books: @books %>

    <div class='body'>
      <div class='container'>

        <p id="notice"><% if flash[:notice] %>
       <%= flash[:notice] %>
<% end %></p>
        <div class='row'>
    <div class="col-lg-3">
<h2>User info</h2>

<div class="profile-container">
  <table class='table'>
    <tr>
       <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "sample-author1.jpg" %>
    </tr>
    <tr>
        <th>name</th>
        <th>
          <%= @users.username %>
        </th>
      <tr>
        <th>introduction</th>
        <th>
          <%= @users.introduction %>
        </th>
      </tr>
</table>

<div class='row'>
    <% if @users == current_user %>
      <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %>
    <% else %>
      <%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench users" %>
    <% end %>
</div>

</div>

<h3>New book</h3>

<%= form_for(@book) do |f| %>

<div class="field row">
<label for="user_name">Title</label>
<%= f.text_field :title, class: "col-xs-12 book_title" %>
</div>

<div class="field row">
<label for="user_name">Opinion</label>
<%= f.text_area :body, class: "col-xs-12 book_body" %>
</div>

<div class="field row">
<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
<% end %>
</div>

</div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag @users, :profile_image, :fill, 40, 40, fallback: "sample-author1.jpg" %></td>
        <td><%= link_to "#{book.title}", "#{book_path(book.id)}", class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
  		 <% end %>
    </tr>
</tbody>
  </thead>

</table>

</div>
</div>
</div>
    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>